function photo() {
    document.getElementById("textPhoto").innerHTML = "Sesja zdjęciowa w plenerze lub w studio: 200 zł</br> Sesja zdjęciowa w plenerze i w studio: 300 zł</br> Sesja zdjęciowa w plenerze i w studio + makijaż: 400 zł</br> Sesja zdjęciowa w plenerze i w studio + makijaż + fryzura: 500 zł</br> Sesja zdjęciowa w plenerze i w studio + makijaż + fryzura + stylizacja: 600 zł</br> Sesja zdjęciowa w plenerze i w studio + makijaż + fryzura + stylizacja + 5 zdjęć w formacie 15x21: 700 zł</br> Sesja zdjęciowa w plenerze i w studio + makijaż + fryzura + stylizacja + 10 zdjęć w formacie 15x21: 800 zł</br> Sesja zdjęciowa w plenerze i w studio + makijaż + fryzura + stylizacja + 15 zdjęć w formacie 15x21: 900 zł</br> Sesja zdjęciowa w plenerze i w studio + makijaż + fryzura + stylizacja + 20 zdjęć w formacie 15x21: 1000 zł</br> Sesja zdjęciowa w plenerze i w studio + makijaż + fryzura + stylizacja + 25 zdjęć w formacie 15x21: 1100 zł</br>";
    document.getElementById("photoDiv").src = "../img/8.jpg"
}

function movies() {
    document.getElementById("textMovies").innerHTML = "Filmowanie wesel, studniówek, komunii, chrzcin, urodzin, imprez okolicznościowych, teledysków, reklam, spotów, filmów promocyjnych,  filmów szkoleniowych: 1000 zł</br> Filmowanie wesel, studniówek, komunii, chrzcin, urodzin, imprez okolicznościowych, teledysków, reklam, spotów, filmów promocyjnych,  filmów szkoleniowych + montaż: 1500 zł</br> Filmowanie wesel, studniówek, komunii, chrzcin, urodzin, imprez okolicznościowych, teledysków, reklam, spotów, filmów promocyjnych,  filmów szkoleniowych + montaż + 5 zdjęć w formacie 15x21: 1600 zł</br> Filmowanie wesel, studniówek, komunii, chrzcin, urodzin, imprez okolicznościowych, teledysków, reklam, spotów, filmów promocyjnych,  filmów szkoleniowych + montaż + 10 zdjęć w formacie 15x21: 1700 zł</br> Filmowanie wesel, studniówek, komunii, chrzcin, urodzin, imprez okolicznościowych, teledysków, reklam, spotów, filmów promocyjnych,  filmów szkoleniowych + montaż + 15 zdjęć w formacie 15x21: 1800 zł</br> Filmowanie wesel, studniówek, komunii, chrzcin, urodzin, imprez okolicznościowych, teledysków, reklam, spotów, filmów promocyjnych,  filmów szkoleniowych + montaż + 20 zdjęć w formacie 15x21: 1900 zł</br> "
    document.getElementById("textMovies").style.width = "50%";
    document.getElementById("moviesDiv").src = "../img/10.jpg"
}